RB3_API_STATIC_INLINE
int headcmp(OUTER_HEAD *head, COMPARE_TYPE *data);

RB3_API RB3_NEVERINLINE
OUTER_HEAD_TYPE *find_in_subtree(OUTER_HEAD_TYPE *subtree, COMPARE_TYPE *cdata);

RB3_API RB3_NEVERINLINE
OUTER_HEAD_TYPE *find_parent_in_subtree(OUTER_HEAD_TYPE *parent, int dir, COMPARE_TYPE *cdata, OUTER_HEAD_TYPE **parent_out, int *dir_out);

RB3_API RB3_NEVERINLINE
OUTER_HEAD_TYPE *delete_in_subtree(COMPARE_TYPE *cdata, OUTER_HEAD_TYPE *subtree);

RB3_API RB3_NEVERINLINE
OUTER_HEAD_TYPE *insert_in_subtree(OUTER_HEAD_TYPE *head, OUTER_HEAD_TYPE *parent, int dir, COMPARE_TYPE *cdata);

RB3_API_INLINE
OUTER_HEAD_TYPE *find(OUTER_TREE_TYPE *tree, COMPARE_TYPE *cdata);

RB3_API_INLINE
OUTER_HEAD_TYPE *delete(COMPARE_TYPE *cdata, OUTER_TREE_TYPE *tree);

RB3_API_INLINE
OUTER_HEAD_TYPE *insert(NODE_TYPE *node, OUTER_TREE_TYPE *tree, COMPARE_TYPE *cdata);
